In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_excel('multi-emotion.xlsx')

In [3]:
df.head()

id                                              Tweet  anger  \
0  2017-En-21441  “Worry is a down payment on a problem you ma...      0   
1  2017-En-31535  Whatever you decide to do make sure it makes y...      0   
2  2017-En-21068  @Max_Kellerman  it also helps that the majorit...      1   
3  2017-En-31436  Accept the challenges so that you can literall...      0   
4  2017-En-22195  My roommate: it's okay that we can't spell bec...      1   

   disgust  fear  joy  sadness  surprise  
0        0     0    0        0         0  
1        0     0    1        0         0  
2        1     0    1        0         0  
3        0     0    1        0         0  
4        1     0    0        0         0

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
import re
import sys
import warnings
data = df
if not sys.warnoptions:
    warnings.simplefilter("ignore")
def cleanHtml(sentence):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, ' ', str(sentence))
    return cleantext
def cleanPunc(sentence): #function to clean the word of any punctuation or special characters
    cleaned = re.sub(r'[?|!|\'|"|#]',r'',sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    cleaned = cleaned.strip()
    cleaned = cleaned.replace("\n"," ")
    return cleaned
def keepAlpha(sentence):
    alpha_sent = ""
    for word in sentence.split():
        alpha_word = re.sub('[^a-z A-Z]+', ' ', word)
        alpha_sent += alpha_word
        alpha_sent += " "
    alpha_sent = alpha_sent.strip()
    return alpha_sent
data['Tweet'] = data['Tweet'].str.lower()
data['Tweet'] = data['Tweet'].apply(cleanHtml)
data['Tweet'] = data['Tweet'].apply(cleanPunc)
data['Tweet'] = data['Tweet'].apply(keepAlpha)

In [5]:
data.head()

id                                              Tweet  anger  \
0  2017-En-21441  worry is a down payment on a problem you may n...      0   
1  2017-En-31535  whatever you decide to do make sure it makes y...      0   
2  2017-En-21068  max kellerman it also helps that the majority ...      1   
3  2017-En-31436  accept the challenges so that you can literall...      0   
4  2017-En-22195  my roommate  its okay that we cant spell becau...      1   

   disgust  fear  joy  sadness  surprise  
0        0     0    0        0         0  
1        0     0    1        0         0  
2        1     0    1        0         0  
3        0     0    1        0         0  
4        1     0    0        0         0

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(min_df=2, max_df=0.5, ngram_range=(1, 2))
features = tfidf.fit_transform(df['Tweet'])
XX = pd.DataFrame(
    features.todense(),
    columns=tfidf.get_feature_names()
)

In [14]:
XX.head()

aaaaarrrrgghhh  aaaaarrrrgghhh iwanttocancel  aaahhhh  aaahhhh little  \
0             0.0                           0.0      0.0             0.0   
1             0.0                           0.0      0.0             0.0   
2             0.0                           0.0      0.0             0.0   
3             0.0                           0.0      0.0             0.0   
4             0.0                           0.0      0.0             0.0   

   aaron  aaron beck  aateam   ab  ab workout  abc       ...        zombie  \
0    0.0         0.0     0.0  0.0         0.0  0.0       ...           0.0   
1    0.0         0.0     0.0  0.0         0.0  0.0       ...           0.0   
2    0.0         0.0     0.0  0.0         0.0  0.0       ...           0.0   
3    0.0         0.0     0.0  0.0         0.0  0.0       ...           0.0   
4    0.0         0.0     0.0  0.0         0.0  0.0       ...           0.0   

   zombiecalorie  zombiecalorie angel  zombies  zombies angels  zones  \
0            0.0                  0.0      0.0             0.0    0.0   
1            0.0                  0.0      0.0             0.0    0.0   
2            0.0                  0.0      0.0             0.0    0.0   
3            0.0                  0.0      0.0             0.0    0.0   
4            0.0                  0.0      0.0             0.0    0.0   

   zones are  zoolander  zrlondon  zrlondon ditto  
0        0.0        0.0       0.0             0.0  
1        0.0        0.0       0.0             0.0  
2        0.0        0.0       0.0             0.0  
3        0.0        0.0       0.0             0.0  
4        0.0        0.0       0.0             0.0  

[5 rows x 23616 columns]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
Y1 = df['joy']

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [19]:
knn = KNeighborsClassifier(n_neighbors=5)

In [20]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(XX, Y1, test_size=0.33, random_state=42)

In [21]:
knn.fit(X_train_1, y_train_1)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [22]:
YYY = knn.predict(X_test_1)
print (YYY)

[0 0 1 ... 0 0 0]


In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_1, YYY)

0.7120070890562694

In [25]:
Y2 = df['anger']

In [26]:
Y3 = df['disgust']

In [27]:
Y4 = df['fear']

In [28]:
Y5 = df['sadness']

In [29]:
Y6 = df['surprise']

In [30]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(XX, Y2, test_size=0.33, random_state=42)
knn.fit(X_train_2, y_train_2)
YY2 = knn.predict(X_test_2)
print (YY2)
accuracy_score(y_test_2, YY2)

[0 1 0 ... 1 0 1]


0.7018165706690297

In [31]:
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(XX, Y3, test_size=0.33, random_state=42)
knn.fit(X_train_3, y_train_3)
YY3 = knn.predict(X_test_3)
print (YY3)
accuracy_score(y_test_3, YY3)

[1 1 0 ... 1 0 1]


0.6774479397430218

In [32]:
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(XX, Y4, test_size=0.33, random_state=42)
knn.fit(X_train_4, y_train_4)
YY4 = knn.predict(X_test_4)
print (YY4)
accuracy_score(y_test_4, YY4)

[0 0 1 ... 0 0 0]


0.8112538768276473

In [33]:
X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(XX, Y5, test_size=0.33, random_state=42)
knn.fit(X_train_5, y_train_5)
YY5 = knn.predict(X_test_5)
print (YY5)
accuracy_score(y_test_5, YY5)

[1 0 0 ... 0 0 0]


0.7009304386353566

In [34]:
X_train_6, X_test_6, y_train_6, y_test_6 = train_test_split(XX, Y6, test_size=0.33, random_state=42)
knn.fit(X_train_6, y_train_6)
YY6 = knn.predict(X_test_6)
print (YY6)
accuracy_score(y_test_6, YY6)

[0 0 0 ... 0 0 0]


0.9428444838280904